import { BrowserRouter, Routes, Route } from "react-router-dom";
import Login from "../pages/Login/Login";

// Comment these temporarily
// import MainLayout ...
// import Dashboard ...
// import GPUNodes ...
// import Jobs ...
// import Monitoring ...
// import History ...
// import Scheduler ...
// import AIScheduler ...
// import { isAuthenticated } ...